name: ads.txt
on:
  push:	
    branches:	
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build ads.txt
      run: |
        mkdir out
        go run main.go > out/ads.txt
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@b49deba147abd18b4fc04bc53c48555ab25dda66
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: out 
     
